/*jshint moz:true */
// vi: sw=2 sts=2 et
(function main () {
  const makeExchangeData = function (tickerData)
      Object.keys(tickerData).reduce(function (o, k) {
          if (k !== "timestamp") {
              o[k] = Object.keys(tickerData[k]).sort(function (a, b)
                tickerData[k][b].volume_btc - tickerData[k][a].volume_btc
              );
          }
          return o;
      }, {});

  if (this.ARGV !== undefined) {
    const Soup = imports.gi.Soup;
    const _httpSession = new Soup.SessionAsync();
    const url = "https://api.bitcoinaverage.com/exchanges/all";
    _httpSession.queue_message(
      Soup.Message.new("GET", url),
      function (session, message) {
        let json = message.response_body.data;
        let data = makeExchangeData(JSON.parse(json));
        print("/*jshint moz:true */");
        print("/* generated by util/MakeExchangeData.js */");
        print("const ExchangeData = " + JSON.stringify(data, null, 4) + ";");
        imports.mainloop.quit("main");
      }
    );

    imports.mainloop.run("main");
  }
})();
