/*jshint moz:true */
// vi: sw=2 sts=2 et
const Soup = imports.gi.Soup;
const _httpSession = new Soup.SessionAsync();
const url = "https://apiv2.bitcoinaverage.com/exchanges/all";

const main = () => {
  const message = Soup.Message.new("GET", url);
  message.request_headers.append("X-testing", "testing");
  _httpSession.queue_message(
    message,
    (session, message) => {
      let json = message.response_body.data;
      let data = JSON.parse(json);
      print("/* generated by util/MakeExchangeData.js */");
      print("const ExchangeData = " + JSON.stringify(data, null, 4) + ";");
      imports.mainloop.quit("main");
    }
  );

  imports.mainloop.run("main");
}

main();

