/* generated by util/MakeExchangeData.js */
const ExchangeData = {
    "AUD": [
        "mtgox",
        "localbitcoins",
        "btcmarkets"
    ],
    "BRL": [
        "mercado",
        "localbitcoins"
    ],
    "CAD": [
        "cavirtex",
        "mtgox",
        "localbitcoins"
    ],
    "CNY": [
        "btcchina",
        "fxbtc",
        "btctrade",
        "bter",
        "rmbtb",
        "goxbtc",
        "bitxf",
        "mtgox",
        "anx_hk"
    ],
    "CZK": [
        "localbitcoins",
        "bitcash"
    ],
    "EUR": [
        "mtgox",
        "bitcoin_de",
        "btce",
        "localbitcoins",
        "kraken",
        "bitcurex",
        "rocktrading",
        "justcoin",
        "intersango",
        "vircurex"
    ],
    "GBP": [
        "mtgox",
        "localbitcoins",
        "bitbargain",
        "bittylicious"
    ],
    "ILS": [
        "bit2c"
    ],
    "JPY": [
        "mtgox"
    ],
    "NOK": [
        "justcoin",
        "localbitcoins"
    ],
    "NZD": [
        "bitnz",
        "mtgox",
        "localbitcoins"
    ],
    "PLN": [
        "bitcurex",
        "mtgox",
        "bidextreme"
    ],
    "RUB": [
        "btce",
        "mtgox"
    ],
    "SEK": [
        "mtgox",
        "fybse",
        "kapiton",
        "localbitcoins"
    ],
    "SGD": [
        "fybsg",
        "mtgox",
        "localbitcoins"
    ],
    "USD": [
        "mtgox",
        "btce",
        "bitstamp",
        "bitfinex",
        "localbitcoins",
        "cryptotrade",
        "bitkonan",
        "anx_hk",
        "kraken",
        "vircurex",
        "justcoin",
        "campbx"
    ],
    "ZAR": [
        "localbitcoins",
        "bitx"
    ]
};
