/*jshint moz:true */
/* generated by util/MakeExchangeData.js */
const ExchangeData = {
    "AUD": [
        "localbitcoins",
        "btcmarkets",
        "weex"
    ],
    "BRL": [
        "mercado",
        "localbitcoins"
    ],
    "CAD": [
        "cavirtex",
        "vaultofsatoshi",
        "quadrigacx",
        "localbitcoins"
    ],
    "CHF": [
        "localbitcoins"
    ],
    "CNY": [
        "btcchina",
        "bter",
        "bitxf",
        "localbitcoins",
        "anx_hk"
    ],
    "EUR": [
        "kraken",
        "bitcoin_de",
        "bitonic",
        "btce",
        "bitcoin_central",
        "localbitcoins",
        "itbit",
        "justcoin",
        "rocktrading",
        "bitcurex",
        "vircurex",
        "intersango",
        "btceur"
    ],
    "GBP": [
        "localbitcoins",
        "bitbargain",
        "bittylicious",
        "quickbitcoin",
        "bit121"
    ],
    "ILS": [
        "bit2c"
    ],
    "JPY": [
        "localbitcoins"
    ],
    "NOK": [
        "justcoin",
        "localbitcoins"
    ],
    "NZD": [
        "bitnz",
        "localbitcoins"
    ],
    "PLN": [
        "bitcurex",
        "localbitcoins"
    ],
    "RUB": [
        "btce",
        "localbitcoins"
    ],
    "SEK": [
        "fybse",
        "localbitcoins",
        "kapiton"
    ],
    "SGD": [
        "fybsg",
        "itbit",
        "localbitcoins"
    ],
    "TRY": [
        "btcturk"
    ],
    "THB": [
        "bxinth"
    ],
    "USD": [
        "bitstamp",
        "btce",
        "bitfinex",
        "itbit",
        "localbitcoins",
        "campbx",
        "vaultofsatoshi",
        "kraken",
        "anx_hk",
        "vircurex",
        "bitkonan",
        "justcoin",
        "rocktrading",
        "cryptotrade"
    ],
    "ZAR": [
        "bitx",
        "localbitcoins"
    ]
};
