/*jshint moz:true */
/* generated by util/MakeExchangeData.js */
const ExchangeData = {
    "AUD": [
        "btcmarkets",
        "independentreserve"
    ],
    "BRL": [
        "foxbit",
        "mercado",
        "bitcointoyou",
        "negociecoins"
    ],
    "CAD": [
        "quadrigacx",
        "taurus",
        "kraken"
    ],
    "CNY": [
        "btc38"
    ],
    "EUR": [
        "zyado",
        "kraken",
        "bitstamp",
        "gdax",
        "rocktrading",
        "bitonic",
        "bl3p",
        "btce",
        "paymium",
        "coinmate",
        "itbit",
        "bitbay",
        "bitsquare",
        "bittylicious",
        "hitbtc",
        "cryptonit"
    ],
    "GBP": [
        "coinfloor",
        "gdax",
        "bittylicious",
        "bitbargain",
        "quickbitcoin"
    ],
    "IDR": [
        "bitcoin_co_id",
        "bitx"
    ],
    "ILS": [
        "bit2c"
    ],
    "INR": [
        "btcxindia",
        "coinsecure"
    ],
    "JPY": [
        "kraken"
    ],
    "KRW": [
        "korbit"
    ],
    "MXN": [
        "bitso"
    ],
    "MYR": [
        "bitx"
    ],
    "NGN": [
        "bitx"
    ],
    "PLN": [
        "bitbay"
    ],
    "RUB": [
        "exmoney",
        "btce"
    ],
    "SEK": [
        "fybse"
    ],
    "SGD": [
        "itbit",
        "fybsg"
    ],
    "TRY": [
        "btcturk"
    ],
    "USD": [
        "gdax",
        "bitfinex",
        "btce",
        "bitstamp",
        "gemini",
        "kraken",
        "cex",
        "itbit",
        "exmoney",
        "independentreserve",
        "hitbtc",
        "rocktrading",
        "quadrigacx",
        "bitsquare",
        "cryptonit",
        "bitex",
        "bitt"
    ],
    "ZAR": [
        "bitx"
    ]
};
