/*jshint moz:true */
/* generated by util/MakeProviderKrakenAssetPairs.js */
var AssetPairs = {
    "BCHEUR": {
        "altname": "BCHEUR",
        "base": "BCH",
        "quote": "ZEUR",
        "pair_decimals": 1
    },
    "BCHUSD": {
        "altname": "BCHUSD",
        "base": "BCH",
        "quote": "ZUSD",
        "pair_decimals": 1
    },
    "BCHXBT": {
        "altname": "BCHXBT",
        "base": "BCH",
        "quote": "XXBT",
        "pair_decimals": 5
    },
    "DASHEUR": {
        "altname": "DASHEUR",
        "base": "DASH",
        "quote": "ZEUR",
        "pair_decimals": 3
    },
    "DASHUSD": {
        "altname": "DASHUSD",
        "base": "DASH",
        "quote": "ZUSD",
        "pair_decimals": 3
    },
    "DASHXBT": {
        "altname": "DASHXBT",
        "base": "DASH",
        "quote": "XXBT",
        "pair_decimals": 5
    },
    "EOSETH": {
        "altname": "EOSETH",
        "base": "EOS",
        "quote": "XETH",
        "pair_decimals": 6
    },
    "EOSXBT": {
        "altname": "EOSXBT",
        "base": "EOS",
        "quote": "XXBT",
        "pair_decimals": 7
    },
    "GNOETH": {
        "altname": "GNOETH",
        "base": "GNO",
        "quote": "XETH",
        "pair_decimals": 4
    },
    "GNOXBT": {
        "altname": "GNOXBT",
        "base": "GNO",
        "quote": "XXBT",
        "pair_decimals": 5
    },
    "USDTZUSD": {
        "altname": "USDTUSD",
        "base": "USDT",
        "quote": "ZUSD",
        "pair_decimals": 4
    },
    "XETCXETH": {
        "altname": "ETCETH",
        "base": "XETC",
        "quote": "XETH",
        "pair_decimals": 6
    },
    "XETCXXBT": {
        "altname": "ETCXBT",
        "base": "XETC",
        "quote": "XXBT",
        "pair_decimals": 6
    },
    "XETCZEUR": {
        "altname": "ETCEUR",
        "base": "XETC",
        "quote": "ZEUR",
        "pair_decimals": 3
    },
    "XETCZUSD": {
        "altname": "ETCUSD",
        "base": "XETC",
        "quote": "ZUSD",
        "pair_decimals": 3
    },
    "XETHXXBT": {
        "altname": "ETHXBT",
        "base": "XETH",
        "quote": "XXBT",
        "pair_decimals": 5
    },
    "XETHZCAD": {
        "altname": "ETHCAD",
        "base": "XETH",
        "quote": "ZCAD",
        "pair_decimals": 2
    },
    "XETHZEUR": {
        "altname": "ETHEUR",
        "base": "XETH",
        "quote": "ZEUR",
        "pair_decimals": 2
    },
    "XETHZGBP": {
        "altname": "ETHGBP",
        "base": "XETH",
        "quote": "ZGBP",
        "pair_decimals": 2
    },
    "XETHZJPY": {
        "altname": "ETHJPY",
        "base": "XETH",
        "quote": "ZJPY",
        "pair_decimals": 0
    },
    "XETHZUSD": {
        "altname": "ETHUSD",
        "base": "XETH",
        "quote": "ZUSD",
        "pair_decimals": 2
    },
    "XICNXETH": {
        "altname": "ICNETH",
        "base": "XICN",
        "quote": "XETH",
        "pair_decimals": 6
    },
    "XICNXXBT": {
        "altname": "ICNXBT",
        "base": "XICN",
        "quote": "XXBT",
        "pair_decimals": 6
    },
    "XLTCXXBT": {
        "altname": "LTCXBT",
        "base": "XLTC",
        "quote": "XXBT",
        "pair_decimals": 6
    },
    "XLTCZEUR": {
        "altname": "LTCEUR",
        "base": "XLTC",
        "quote": "ZEUR",
        "pair_decimals": 2
    },
    "XLTCZUSD": {
        "altname": "LTCUSD",
        "base": "XLTC",
        "quote": "ZUSD",
        "pair_decimals": 2
    },
    "XMLNXETH": {
        "altname": "MLNETH",
        "base": "XMLN",
        "quote": "XETH",
        "pair_decimals": 5
    },
    "XMLNXXBT": {
        "altname": "MLNXBT",
        "base": "XMLN",
        "quote": "XXBT",
        "pair_decimals": 6
    },
    "XREPXETH": {
        "altname": "REPETH",
        "base": "XREP",
        "quote": "XETH",
        "pair_decimals": 5
    },
    "XREPXXBT": {
        "altname": "REPXBT",
        "base": "XREP",
        "quote": "XXBT",
        "pair_decimals": 6
    },
    "XREPZEUR": {
        "altname": "REPEUR",
        "base": "XREP",
        "quote": "ZEUR",
        "pair_decimals": 3
    },
    "XXBTZCAD": {
        "altname": "XBTCAD",
        "base": "XXBT",
        "quote": "ZCAD",
        "pair_decimals": 1
    },
    "XXBTZEUR": {
        "altname": "XBTEUR",
        "base": "XXBT",
        "quote": "ZEUR",
        "pair_decimals": 1
    },
    "XXBTZGBP": {
        "altname": "XBTGBP",
        "base": "XXBT",
        "quote": "ZGBP",
        "pair_decimals": 1
    },
    "XXBTZJPY": {
        "altname": "XBTJPY",
        "base": "XXBT",
        "quote": "ZJPY",
        "pair_decimals": 0
    },
    "XXBTZUSD": {
        "altname": "XBTUSD",
        "base": "XXBT",
        "quote": "ZUSD",
        "pair_decimals": 1
    },
    "XXDGXXBT": {
        "altname": "XDGXBT",
        "base": "XXDG",
        "quote": "XXBT",
        "pair_decimals": 8
    },
    "XXLMXXBT": {
        "altname": "XLMXBT",
        "base": "XXLM",
        "quote": "XXBT",
        "pair_decimals": 8
    },
    "XXMRXXBT": {
        "altname": "XMRXBT",
        "base": "XXMR",
        "quote": "XXBT",
        "pair_decimals": 6
    },
    "XXMRZEUR": {
        "altname": "XMREUR",
        "base": "XXMR",
        "quote": "ZEUR",
        "pair_decimals": 2
    },
    "XXMRZUSD": {
        "altname": "XMRUSD",
        "base": "XXMR",
        "quote": "ZUSD",
        "pair_decimals": 2
    },
    "XXRPXXBT": {
        "altname": "XRPXBT",
        "base": "XXRP",
        "quote": "XXBT",
        "pair_decimals": 8
    },
    "XXRPZEUR": {
        "altname": "XRPEUR",
        "base": "XXRP",
        "quote": "ZEUR",
        "pair_decimals": 5
    },
    "XXRPZUSD": {
        "altname": "XRPUSD",
        "base": "XXRP",
        "quote": "ZUSD",
        "pair_decimals": 5
    },
    "XZECXXBT": {
        "altname": "ZECXBT",
        "base": "XZEC",
        "quote": "XXBT",
        "pair_decimals": 5
    },
    "XZECZEUR": {
        "altname": "ZECEUR",
        "base": "XZEC",
        "quote": "ZEUR",
        "pair_decimals": 3
    },
    "XZECZUSD": {
        "altname": "ZECUSD",
        "base": "XZEC",
        "quote": "ZUSD",
        "pair_decimals": 2
    }
};
