/* generated by util/MakeExchangeData.js */
const ExchangeData = [
    {
        "name": "campbx",
        "display_name": "CampBX",
        "url": "https://campbx.com",
        "timestamp": 1496835602,
        "data_source": "api",
        "symbols": {
            "BTCUSD": {
                "last": 2499,
                "volume": 0.39,
                "ask": 2499,
                "bid": 1444
            }
        }
    },
    {
        "name": "gdax",
        "display_name": "GDAX",
        "url": "https://www.gdax.com/",
        "timestamp": 1496835651,
        "data_source": "api",
        "symbols": {
            "BTCEUR": {
                "last": 2553.03,
                "volume": 2667.08,
                "ask": 2553.03,
                "bid": 2552.04
            },
            "ETHUSD": {
                "last": 264.16,
                "volume": 252861.2025,
                "ask": 264.3,
                "bid": 264.13
            },
            "BTCUSD": {
                "last": 2846.78,
                "volume": 22200.25,
                "ask": 2848.17,
                "bid": 2846.35
            },
            "ETHBTC": {
                "last": 0.0926,
                "volume": 12535.6788,
                "ask": 0.0926,
                "bid": 0.0926
            },
            "BTCGBP": {
                "last": 2217.47,
                "volume": 718.26,
                "ask": 2217.35,
                "bid": 2215.45
            }
        }
    },
    {
        "name": "bitcoin_co_id",
        "display_name": "Bitcoin.co.id",
        "url": "https://bitcoin.co.id/",
        "timestamp": 1496835656,
        "data_source": "api",
        "symbols": {
            "BTCIDR": {
                "last": 38920000,
                "volume": 739.12,
                "ask": 38920000,
                "bid": 38915000
            }
        }
    },
    {
        "name": "rocktrading",
        "display_name": "Rock Trading",
        "url": "https://therocktrading.com/",
        "timestamp": 1496835649,
        "data_source": "api",
        "symbols": {
            "BTCEUR": {
                "last": 2495,
                "volume": 1083.34,
                "ask": 2516.33,
                "bid": 2494.92
            },
            "BTCUSD": {
                "last": 2882.67,
                "volume": 5.5,
                "ask": 2928.94,
                "bid": 2889.54
            }
        }
    },
    {
        "name": "okcoin",
        "display_name": "OKCoin",
        "url": "https://www.okcoin.cn/",
        "timestamp": 1496835672,
        "data_source": "api",
        "symbols": {
            "BTCCNY": {
                "last": 19550,
                "volume": 18283.97,
                "ask": 19555,
                "bid": 19550
            }
        }
    },
    {
        "name": "independentreserve",
        "display_name": "Independent Reserve",
        "url": "https://www.independentreserve.com/",
        "timestamp": 1496835647,
        "data_source": "api",
        "symbols": {
            "BTCNZD": {
                "last": 4211.72,
                "volume": 4.01,
                "ask": 4162.64,
                "bid": 4000
            },
            "BTCUSD": {
                "last": 2960,
                "volume": 5.8,
                "ask": 2959.99,
                "bid": 2900
            },
            "BTCAUD": {
                "last": 3880,
                "volume": 141.5,
                "ask": 3880,
                "bid": 3856
            }
        }
    },
    {
        "name": "paymium",
        "display_name": "Paymium",
        "url": "https://paymium.com",
        "timestamp": 1496835667,
        "data_source": "api",
        "symbols": {
            "BTCEUR": {
                "last": 2530,
                "volume": 81.42,
                "ask": 2530,
                "bid": 2520
            }
        }
    },
    {
        "name": "btcmarkets",
        "display_name": "BTC Markets",
        "url": "https://btcmarkets.net/",
        "timestamp": 1496835604,
        "data_source": "api",
        "symbols": {
            "BTCAUD": {
                "last": 3900,
                "volume": 337.73,
                "ask": 3899.99,
                "bid": 3872
            }
        }
    },
    {
        "name": "bl3p",
        "display_name": "BL3P",
        "url": "https://bl3p.eu/",
        "timestamp": 1496835610,
        "data_source": "api",
        "symbols": {
            "BTCEUR": {
                "last": 2540.31,
                "volume": 417.63,
                "ask": 2538.16,
                "bid": 2523.54
            }
        }
    },
    {
        "name": "coinsecure",
        "display_name": "Coinsecure",
        "url": "https://coinsecure.in/",
        "timestamp": 1496835647,
        "data_source": "api",
        "symbols": {
            "BTCINR": {
                "last": 196899.86,
                "volume": 106.47,
                "ask": 196899.98,
                "bid": 196100
            }
        }
    },
    {
        "name": "btce",
        "display_name": "BTC-e",
        "url": "https://btc-e.com/",
        "timestamp": 1496835652,
        "data_source": "api",
        "symbols": {
            "BTCRUB": {
                "last": 158038.56,
                "volume": 377.49,
                "ask": 159000,
                "bid": 158038.56
            },
            "BTCEUR": {
                "last": 2440,
                "volume": 113.46,
                "ask": 2440,
                "bid": 2431
            },
            "BTCUSD": {
                "last": 2729.99,
                "volume": 10481.62,
                "ask": 2733,
                "bid": 2730
            },
            "ETHUSD": {
                "last": 252.6,
                "volume": 27741.95,
                "ask": 252.61,
                "bid": 252.6
            },
            "ETHEUR": {
                "last": 226.04,
                "volume": 498.55,
                "ask": 226.54,
                "bid": 224.76
            },
            "ETHBTC": {
                "last": 0.09,
                "volume": 8900.14,
                "ask": 0.09,
                "bid": 0.09
            },
            "LTCUSD": {
                "last": 28.75,
                "volume": 241817.6,
                "ask": 28.84,
                "bid": 28.75
            }
        }
    },
    {
        "name": "coinmate",
        "display_name": "CoinMate",
        "url": "https://coinmate.io/",
        "timestamp": 1496835649,
        "data_source": "api",
        "symbols": {
            "BTCEUR": {
                "last": 2531,
                "volume": 177.14,
                "ask": 2534.96,
                "bid": 2517.38
            },
            "BTCCZK": {
                "last": 67164.84,
                "volume": 125.8,
                "ask": 67125.17,
                "bid": 66503
            }
        }
    },
    {
        "name": "bitbargain",
        "display_name": "BitBargain",
        "url": "https://bitbargain.co.uk/",
        "timestamp": 1496835654,
        "data_source": "api",
        "symbols": {
            "BTCGBP": {
                "last": 2321.79,
                "volume": 47.34,
                "ask": 2321.79,
                "bid": 2321.79
            }
        }
    },
    {
        "name": "negociecoins",
        "display_name": "Negocie Coins",
        "url": "http://www.negociecoins.com.br/",
        "timestamp": 1496835656,
        "data_source": "api",
        "symbols": {
            "BTCBRL": {
                "last": 9870,
                "volume": 27.99,
                "ask": 10130,
                "bid": 9870
            }
        }
    },
    {
        "name": "bitso",
        "display_name": "Bitso",
        "url": "https://bitso.com/",
        "timestamp": 1496835626,
        "data_source": "api",
        "symbols": {
            "BTCMXN": {
                "last": 53150,
                "volume": 670.57,
                "ask": 53149.96,
                "bid": 52506.06
            }
        }
    },
    {
        "name": "coinfloor",
        "display_name": "Coinfloor",
        "url": "https://coinfloor.co.uk/",
        "timestamp": 1496835665,
        "data_source": "api",
        "symbols": {
            "BTCGBP": {
                "last": 2209,
                "volume": 1023.03,
                "ask": 2209,
                "bid": 2207
            }
        }
    },
    {
        "name": "bitbay",
        "display_name": "BitBay",
        "url": "https://www.bitbay.net",
        "timestamp": 1496835654,
        "data_source": "api",
        "symbols": {
            "BTCEUR": {
                "last": 2598.22,
                "volume": 44.3,
                "ask": 2597.97,
                "bid": 2552
            },
            "BTCPLN": {
                "last": 10660,
                "volume": 2631.14,
                "ask": 10660,
                "bid": 10633.33
            }
        }
    },
    {
        "name": "quickbitcoin",
        "display_name": "QuickBitcoin",
        "url": "https://quickbitcoin.co.uk/",
        "timestamp": 1496835648,
        "data_source": "api",
        "symbols": {
            "BTCGBP": {
                "last": 2395.2,
                "volume": 7.16,
                "ask": 2395.2,
                "bid": 2395.2
            }
        }
    },
    {
        "name": "hitbtc",
        "display_name": "Hitbtc",
        "url": "https://hitbtc.com/",
        "timestamp": 1496835658,
        "data_source": "api",
        "symbols": {
            "BTCEUR": {
                "last": 2398.99,
                "volume": 0.14,
                "ask": 2449.97,
                "bid": 1011.45
            },
            "BTCUSD": {
                "last": 2810.84,
                "volume": 56.27,
                "ask": 2821.17,
                "bid": 2800
            },
            "LTCUSD": {
                "last": 30.89,
                "volume": 5758.5,
                "ask": 31.79,
                "bid": 29.2
            }
        }
    },
    {
        "name": "btcturk",
        "display_name": "BTCTurk",
        "url": "https://www.btcturk.com/",
        "timestamp": 1496835602,
        "data_source": "api",
        "symbols": {
            "BTCTRY": {
                "last": 10014.99,
                "volume": 419.76,
                "ask": 10014.99,
                "bid": 10000
            }
        }
    },
    {
        "name": "fybsg",
        "display_name": "FYB-SG",
        "url": "https://www.fybsg.com/",
        "timestamp": 1496835623,
        "data_source": "api",
        "symbols": {
            "BTCSGD": {
                "last": 4000,
                "volume": 15.05,
                "ask": 4000,
                "bid": 3980
            }
        }
    },
    {
        "name": "kraken",
        "display_name": "Kraken",
        "url": "https://kraken.com/",
        "timestamp": 1496835657,
        "data_source": "api",
        "symbols": {
            "BTCEUR": {
                "last": 2531,
                "volume": 28401.9,
                "ask": 2531,
                "bid": 2531
            },
            "BTCUSD": {
                "last": 2839,
                "volume": 10122.37,
                "ask": 2844.43,
                "bid": 2839
            },
            "ETHEUR": {
                "last": 234.5,
                "volume": 165543.19,
                "ask": 234.93,
                "bid": 234.5
            },
            "BTCCAD": {
                "last": 3807.35,
                "volume": 168.28,
                "ask": 3882.43,
                "bid": 3810.54
            },
            "ETHUSD": {
                "last": 263.4,
                "volume": 64228.65,
                "ask": 263.4,
                "bid": 263
            },
            "ETHBTC": {
                "last": 0.09,
                "volume": 48205.27,
                "ask": 0.09,
                "bid": 0.09
            },
            "LTCUSD": {
                "last": 30.1,
                "volume": 29684.65,
                "ask": 30.2,
                "bid": 30.1
            },
            "ZECUSD": {
                "last": 297.79,
                "volume": 3489.82,
                "ask": 296,
                "bid": 289.54
            },
            "ZECBTC": {
                "last": 0.1,
                "volume": 5135.75,
                "ask": 0.1,
                "bid": 0.1
            },
            "LTCEUR": {
                "last": 26.8,
                "volume": 80664.49,
                "ask": 26.93,
                "bid": 26.8
            },
            "BTCJPY": {
                "last": 311200,
                "volume": 64.53,
                "ask": 315907.9,
                "bid": 311012.1
            },
            "ZECEUR": {
                "last": 256.19,
                "volume": 5681.45,
                "ask": 261.91,
                "bid": 256.19
            },
            "LTCBTC": {
                "last": 0.01,
                "volume": 38230.21,
                "ask": 0.01,
                "bid": 0.01
            }
        }
    },
    {
        "name": "cryptonit",
        "display_name": "Cryptonit",
        "url": "https://www.cryptonit.net/",
        "timestamp": 1496835602,
        "data_source": "api",
        "symbols": {
            "BTCEUR": {
                "last": 2530.57,
                "volume": 0.01,
                "ask": 2530.57,
                "bid": 2534.79
            },
            "BTCUSD": {
                "last": 2815.28,
                "volume": 0.26,
                "ask": 2815.28,
                "bid": 2736.5
            }
        }
    },
    {
        "name": "jubi",
        "display_name": "Jubi",
        "url": "http://www.jubi.com/",
        "timestamp": 1496835599,
        "data_source": "api",
        "symbols": {
            "LTCCNY": {
                "last": 199.9,
                "volume": 33597.64,
                "ask": 199.9,
                "bid": 199
            }
        }
    },
    {
        "name": "bittylicious",
        "display_name": "Bittylicious",
        "url": "https://bittylicious.com/",
        "timestamp": 1496835650,
        "data_source": "api",
        "symbols": {
            "BTCEUR": {
                "last": 2971.87,
                "volume": 0.52,
                "ask": 2971.87,
                "bid": 2971.87
            },
            "LTCGBP": {
                "last": 26.14,
                "volume": 167.78,
                "ask": 26.14,
                "bid": 26.14
            },
            "BTCGBP": {
                "last": 2364.65,
                "volume": 89.08,
                "ask": 2364.65,
                "bid": 2364.65
            }
        }
    },
    {
        "name": "bitt",
        "display_name": "Bitt",
        "url": "https://www.bitt.com",
        "timestamp": 1496835667,
        "data_source": "api",
        "symbols": {
            "BTCUSD": {
                "last": 1735.71,
                "volume": 103.37,
                "ask": 1955.09,
                "bid": 1914.66
            }
        }
    },
    {
        "name": "bitex",
        "display_name": "Bitex.la",
        "url": "https://bitex.la/",
        "timestamp": 1496835619,
        "data_source": "api",
        "symbols": {
            "BTCUSD": {
                "last": 2855.2,
                "volume": 34.29,
                "ask": 2853.5,
                "bid": 2834.81
            }
        }
    },
    {
        "name": "fybse",
        "display_name": "FYB-SE",
        "url": "https://www.fybse.se/",
        "timestamp": 1496835629,
        "data_source": "api",
        "symbols": {
            "BTCSEK": {
                "last": 26700,
                "volume": 1.63,
                "ask": 26780.88,
                "bid": 24501
            }
        }
    },
    {
        "name": "bitstamp",
        "display_name": "Bitstamp",
        "url": "https://bitstamp.net/",
        "timestamp": 1496835649,
        "data_source": "api",
        "symbols": {
            "BTCEUR": {
                "last": 2540,
                "volume": 4558.25,
                "ask": 2547.78,
                "bid": 2540
            },
            "BTCUSD": {
                "last": 2847.32,
                "volume": 20870.82,
                "ask": 2847.27,
                "bid": 2841.08
            },
            "XRPUSD": {
                "last": 0.2819,
                "volume": 10822575.976,
                "ask": 0.2819,
                "bid": 0.2803
            },
            "XRPEUR": {
                "last": 0.2531,
                "volume": 3469874.9596,
                "ask": 0.2532,
                "bid": 0.2519
            }
        }
    },
    {
        "name": "bitx",
        "display_name": "BitX",
        "url": "https://bitx.co/",
        "timestamp": 1496835593,
        "data_source": "api",
        "symbols": {
            "BTCMYR": {
                "last": 12351,
                "volume": 198.07,
                "ask": 12351,
                "bid": 12328
            },
            "BTCNGN": {
                "last": 1049234,
                "volume": 46.93,
                "ask": 1049235,
                "bid": 1049234
            },
            "BTCZAR": {
                "last": 39961,
                "volume": 680.24,
                "ask": 39990,
                "bid": 39970
            },
            "BTCIDR": {
                "last": 38705000,
                "volume": 12.3,
                "ask": 38800000,
                "bid": 38705000
            }
        }
    },
    {
        "name": "exmoney",
        "display_name": "Exmoney",
        "url": "https://exmoney.com/",
        "timestamp": 1496835602,
        "data_source": "api",
        "symbols": {
            "BTCRUB": {
                "last": 156000,
                "volume": 222.54,
                "ask": 156550,
                "bid": 156000
            },
            "BTCUSD": {
                "last": 2730,
                "volume": 185.15,
                "ask": 2730,
                "bid": 2722
            }
        }
    },
    {
        "name": "quadrigacx",
        "display_name": "QuadrigaCX",
        "url": "https://quadrigacx.com/",
        "timestamp": 1496835603,
        "data_source": "api",
        "symbols": {
            "BTCUSD": {
                "last": 2890,
                "volume": 20.62,
                "ask": 2950,
                "bid": 2850.02
            },
            "BTCCAD": {
                "last": 3945,
                "volume": 709.56,
                "ask": 3945,
                "bid": 3920.01
            }
        }
    },
    {
        "name": "huobi",
        "display_name": "Huobi",
        "url": "https://www.huobi.com/",
        "timestamp": 1496835585,
        "data_source": "api",
        "symbols": {
            "BTCCNY": {
                "last": 19516,
                "volume": 12962.32,
                "ask": 19517.3,
                "bid": 19516
            }
        }
    },
    {
        "name": "foxbit",
        "display_name": "Foxbit",
        "url": "http://www.foxbit.com.br",
        "timestamp": 1496835636,
        "data_source": "api",
        "symbols": {
            "BTCBRL": {
                "last": 10050,
                "volume": 589.58,
                "ask": 10052.26,
                "bid": 10050
            }
        }
    },
    {
        "name": "btcc",
        "display_name": "BTCC",
        "url": "https://btcc.com/",
        "timestamp": 1496835586,
        "data_source": "api",
        "symbols": {
            "LTCCNY": {
                "last": 205,
                "volume": 41020.49,
                "ask": 204.88,
                "bid": 204
            },
            "BTCCNY": {
                "last": 19463.01,
                "volume": 15205.25,
                "ask": 19500,
                "bid": 19463
            }
        }
    },
    {
        "name": "bitonic",
        "display_name": "Bitonic",
        "url": "https://bitonic.nl",
        "timestamp": 1496835649,
        "data_source": "api",
        "symbols": {
            "BTCEUR": {
                "last": 2528.46,
                "volume": 866,
                "ask": 2528.46,
                "bid": 2528.46
            }
        }
    },
    {
        "name": "gemini",
        "display_name": "Gemini",
        "url": "https://www.gemini.com/",
        "timestamp": 1496835602,
        "data_source": "api",
        "symbols": {
            "ETHUSD": {
                "last": 263.91,
                "volume": 65740.69,
                "ask": 263.93,
                "bid": 263.9
            },
            "BTCUSD": {
                "last": 2835.86,
                "volume": 9341.28,
                "ask": 2835.86,
                "bid": 2835.85
            }
        }
    },
    {
        "name": "bit2c",
        "display_name": "Bit2C",
        "url": "https://www.bit2c.co.il/",
        "timestamp": 1496835602,
        "data_source": "api",
        "symbols": {
            "BTCILS": {
                "last": 11099,
                "volume": 59.32,
                "ask": 11050,
                "bid": 10802
            }
        }
    },
    {
        "name": "btc38",
        "display_name": "BTC38",
        "url": "http://btc38.com/",
        "timestamp": 1496835644,
        "data_source": "api",
        "symbols": {
            "LTCCNY": {
                "last": 197.5,
                "volume": 65082.29,
                "ask": 197.5,
                "bid": 197.1
            },
            "BTCCNY": {
                "last": 19220,
                "volume": 1035.73,
                "ask": 19334.9,
                "bid": 19220
            }
        }
    },
    {
        "name": "mercado",
        "display_name": "Mercado Bitcoin",
        "url": "https://www.mercadobitcoin.com.br/",
        "timestamp": 1496835614,
        "data_source": "api",
        "symbols": {
            "BTCBRL": {
                "last": 9998,
                "volume": 460.38,
                "ask": 9998,
                "bid": 9925
            }
        }
    },
    {
        "name": "cex",
        "display_name": "CEX.IO",
        "url": "https://cex.io/",
        "timestamp": 1496835611,
        "data_source": "api",
        "symbols": {
            "ETHUSD": {
                "last": 2899.76,
                "volume": 1157.76,
                "ask": 2900,
                "bid": 2899.76
            },
            "BTCUSD": {
                "last": 2899.76,
                "volume": 1157.76,
                "ask": 2900,
                "bid": 2899.76
            },
            "ETHBTC": {
                "last": 0.09,
                "volume": 2952.99,
                "ask": 0.09,
                "bid": 0.09
            }
        }
    },
    {
        "name": "bitsquare",
        "display_name": "Bitsquare",
        "url": "https://bitsquare.io/",
        "timestamp": 1496835626,
        "data_source": "api",
        "symbols": {
            "BTCEUR": {
                "last": 2547.14,
                "volume": 2.66,
                "ask": 2534.91,
                "bid": null
            },
            "BTCUSD": {
                "last": 2797.73,
                "volume": 4.32,
                "ask": 2920,
                "bid": 2677
            }
        }
    }
];
